# Name of our workflow
name: "Test"

# Events that will trigger our workflow
on: ["pull_request", "push"]

jobs:
    build:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: bahmutov/npm-install@v1

            - run: npm run format
            - run: git status
            # commit any changed files
            # https://github.com/mikeal/publish-to-github-action
            - uses: mikeal/publish-to-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
