---
name: ci

on: [pull_request, push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Format files
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "feat(format): apply formatting changes"
          branch: ${{ github.head_ref }}

  lint:
    runs-on: ubuntu-latest
    needs: [format]
    permissions:
      contents: write
    steps:
      - name: check code out from github and into "ubuntu-latest" (or our environment)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: lint ansible playbook playbook.yml
        uses: ansible/ansible-lint@v25.5.0
        with:
          args: --fix -c ./.ansible-lint
        # continue-on-error: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "feat(lint): apply linting changes"
          branch: ${{ github.head_ref }}
